### ISSUE TITLE
register_every_n_samples_event function doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pearu/pylibnidaqmx#7]
```
What steps will reproduce the problem?
1.connect NI USB-6008 
2.run AI_callback.py

What is the expected output? What do you see instead?
The callback function, processData, should be called around 10 times. It
was called only one time and then report an error.

>>> etner processData
[1.7970646050673522, 1.7984920817111949, 1.7988999321808641,
1.798899932180865, 1.7986960069460296, 1.7978803060066901,
1.7980842312415248, 1.797472455537021, 1.7968606798325175, 1.7976763807718563]
Traceback (most recent call last):
  File
"C:\Python26\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py",
line 322, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=0)
  File
"C:\Python26\Lib\site-packages\pythonwin\pywin\debugger\__init__.py", line
60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File
"C:\Python26\Lib\site-packages\pythonwin\pywin\debugger\debugger.py", line
655, in run
    exec cmd in globals, locals
  File "C:\Python26\AI_callback.py", line 21, in <module>
    task.stop()
  File "C:\Python26\lib\site-packages\nidaqmx\libnidaqmx.py", line 787, in stop
    return CALL('StopTask', self) == 0
  File "C:\Python26\lib\site-packages\nidaqmx\libnidaqmx.py", line 187, in CALL
    r = CHK(r, funcname, *new_args)
  File "C:\Python26\lib\site-packages\nidaqmx\libnidaqmx.py", line 168, in CHK
    raise RuntimeError('%s%s:%s' % (funcname,args, text))
RuntimeError: DAQmxStopTask(AnalogInputTask('_unnamedTask<5>'),):
  Measurements: Task specified is invalid or does not exist.
  ----------


What version of the product are you using? On what operating system?
I am using NI USB-6008 on windows PC.

Please provide any additional information below.
I tried register_done_event with finite AI mode, it has the same the problems. 

```

Original issue reported on code.google.com by `liujiny...@gmail.com` on 28 Apr 2010 at 8:37

Attachments:
- [AI_callback.py](https://storage.googleapis.com/google-code-attachments/pylibnidaqmx/issue-7/comment-0/AI_callback.py)

**Comment by PeterNau** [comment]
I tried to fix this problem for DigitalInputTask.register_signal_event...
(I'm running python 3.5 and using the port_to_py3_testStage branch, and I see no evidence
that the problem is related to that.)
First, I changed the register_every_n_samples_event function by hand, according to nidaq.diff from valhall...@gmail.com on 24 Feb 2011.
I did this to understand the pattern, and then I applied it (as best I could)
to the register_signal_event function.

When I run the code, registration works, but when the callback fires, the following error results:
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
TypeError: fwrapper() missing 1 required positional argument: 'cb_data'
...and the error keeps repeating every time the signal event occurs.

This is tantalizing and looks hopeful, but I have no prior experience with ctypes, and I'm running out of time on my job to get this working.
The diff file is attached (I had to append .txt, since this web site wouldn't accept.

If I can't fix it, then I'll have to use the corresponding (lower-level) functions provided by https://github.com/clade/PyDAQmx, which I'd prefer to avoid.

If anyone can help, I'd appreciate any suggestions or comments.

Thanks.
-Peter
[nidaqmx.diff.txt](https://github.com/pearu/pylibnidaqmx/files/856125/nidaqmx.diff.txt)
